apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: ocp-2048
  namespace: game-2048
spec:
  replicas: 1
  selector:
    app: ocp-2048
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: ocp-2048
    spec:
      containers:
        - name: web
          image: ""  # подставится триггером ImageChange из ImageStreamTag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames: ["web"]
        from:
          kind: ImageStreamTag
          name: ocp-2048:latest
          namespace: game-2048
