apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - imagestream.yaml
  - buildconfig.yaml
  - deploymentconfig.yaml
  - service.yaml
  - route.yaml
namespace: game-2048
